import type { Metadata } from 'next'
import Provider from '@/app/provider';
import Sidebar from '@/components/organisms/Sidebar';
import LoginModal from '@/components/organisms/Modal/Modal';
import { WindowSize } from '@/components/debug/WindowSize';
import { ToastContainer } from '@/utils/Toast';
import './global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'ja_JP',
    url: 'https://nextjs.org/',
    images: [
      {
        url: 'https://api-stg.topicpost.net/v1/og/recreation?id=21efc871-386a-45ea-9f18-c3fbe0775558',
        width: 1200,
        height: 630,
        alt: 'Og Image Alt',
      },
    ],
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <body className={``}>
        <Provider>
          <ToastContainer />
          {/* Sidebarを追加する */}
          <Sidebar />
          {/* メインコンテツ部分を追加する */}
          <div className="p-3 lg:ml-64">
            {children}
          </div>
          {/* デバック用のコンポーネント */}
          <WindowSize />
          <LoginModal />
        </Provider>
      </body>
    </html>
  )
}
